env:
  global:
    - secure: jQBDli0ITHHbN/D2UCzjArTiHYpNGn0tC83fQCqKYHd2ftBB03phABbPiRsoM0yXUozv/1WMhO91jok85MBPkGdXJiISboMU5rq0QX0Dk3QPsgcdK6a+7s8cAoEIFjpCWcJhb/EMBrXGQaNojYEdEt7UwN0gQjUhhmQL7rZCphw3Rl+AVmJXLSGgzYUMWIt2o1psj743ZwLT9GIHPzFpD3COoyDPYJZIwH7octG7wb8Wwl1kAvj+q8BAS63xZVD+Jratf4rLJauvFCZ9CaMFrP8+Fb/MG1ijyEVJeo+rAFdXIUq2HEPDr/MmCMa3tRhYC9Hp4aaJR5slUb7LOWZ3ETOyoOyfWnn+imOA62lkozCDsr6jAEC3H3kvLC6SbSJS3wUSWpJltbehz7kucsViqvt+KL4N4DXvcmOxeLpRIYlpicnDVgx/ICo7bhh/H7SRs1CQc/Xd6961pONMoGvQWoXFCFuxashQrBvkr9PZyL9EbaGadlAyO3NkRXjmKZl1CppTIRK6dHWKvsXlFydn7iiY9eMM6+bc01c47GKEerKg68evdR2i+7YyHwNO14FA40mU4Gcq+W+ZOzuhobhuzOaIUDDA+81ugEGA54wua24RSmw4rezPJxSS4qpVDnWQZNqSoCVujrgCpNjQXn4C5VhPRaSnYA98BiCygc5QBgs=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/malc0de.com
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
