env:
  global:
    - secure: NxIr7hMZNjWrgj0v2CkUGSZzV71r/LkOU/ZebqVm6yb8tL3qImp5VNG25TV13IML1pQKdbVTdsIvVAnSzrafDN624yLLDebU+cu6+jzGll2K8nSIqKNB4p7bsqS7k497iESAp3ocUPDHhD0pidX9j6nrLUJLW0QUoHLotvnbgY7PUPJjdCcbVOPGMkobysARMZaQGR2snlpnq209YbjfX+IA3El1hgW8K1gbClzADTixHhfEiofz213SA6rCB3m0sHP9m5nP8Tn2URx0aF7WUgm31IHFKiHoAU9hXnpjY17fyyxZgdj4RSc7NNdsht6FxM2MnFKxARmqPCtUR+mqOUl+//JNuyXmhFTi6VzkJkMQCl1RMO9EG0pbQqPQAPVGQS49dYoiE1uP6cOSJ2RUNPr9qdVVxxSw0s745TPPJ0LW/a675LzTfu15um8XFgtk8qQhbo3p3beFk1awdiyvojZ1mkEmyc1TK0KUfXBNnbnViHxO6ce5KiKIYP0dv85Ej7DBAlAqKkK5S35YMUp3IV0ZcFzHoqHwXpbpqQ5+SwcKkRV2LVAvcrti5EUOMBxpWwFiPPsOswkxMKflrcqnjXhd3S4eohjZHDvzH5N/AD8e65eMDmDaTI7DllVALcr/iR+yulOuGfU4UEV3Pc8s0jFBcddSXxTjfB6cDNfbHtI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/malc0de.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
