env:
  global:
    - secure: jOTrtRHsXj+2HfMGM8cWPSvvgxwfcvBFgQwTpDWTDNqIVDd1ziHVZBBPocl+pqMHp7ZtDxx+0HiFjed9n5J+e5b8HvjyBgWeZlgUnqmC/ry6aaMZ79zSHyxY8Vgf+Qs9I8Kg4Gm5ow+U9HUrYJ/9bctOJTNSY71QF3mcuGkjQMJ442hK39E7sNPDvLabkLpjFP08DUWc4gb7ye9aAVc0rgkLwQF5nAF5tdAfZmof76ChEWC/T3Qs6kI2md4jpQVtyrerDNg71fCnUl2L5bCeYw/upyPhoh8bT8Kp1xqFINFhfdpJo+NT2a8nZCE48bPm4eobwVjuxgSQ2Ss2ZsNqWcytriTGIRYNgjtgRDbri6bwnqY5tVoREhExoqjg3hi/zC/BYwYvc/IHNbDzvS6YoQQqLpPiTP+8Pj+mn/6h/yBdmp15+K7ieUKCBtUqgNBj6VYOV3p+cTgNIKvWOFFKmhnwS5N6NphP333sD34x29DOmpkDge4m627nABFYIrMLOdxC57j0Neo+i+kd8MUNu2Ent3pCVBus5DOxltog1oCiByFz7dzchmrasU4FxzsPQK4KJF3Qjfq9hssOybgeA4gCREs8WJfOxrIzg5xdeB+BEAPa78i7J+vKZAD7PvBBMabcbFlAFi053OjP9QNbw1rCHhdKhUEfKkU38QXMFck=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/malc0de.com
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
