env:
  global:
    - secure: pZHPxEZhoK72LxqSEttZmXFz5AEs03oCqyVps4BA6kaT2L41e7Bb+q3uIFVlk+7ZQlv5R4ssmOLGN7PPamr+3juUM9xlo7KTrUri/ejpMu++inj1rfvOB9j6vImr0sOAhS/EV2gE6h3WGUHu7DsRwe0WQiS6EcKmj0DekM2+7gFIgZNgKXxB4nUnJllKBRila9gZ3mW/5+WgklJy3Fz1VKQe+cDne8pBV+eKXD0rKzPsv9qa7MNi/OzfZVPJySZRbJHFh+vEDdYrwz+kOdzOcqqr20VwJCM0mkB1rUwNPwh4cYAziIX3iQz2R8/rZu2G7xB6w7i4r5kbJl7FWAKI+QajN6uwd1Q0oMtxSYjhNBVMIqEnm4hM9eU9w2DRQlhC40nxdSo//FAIjfUQFuzBEZdGy/RKPd8JJt+DlZbjIY8ormNVJf7XVDVJNqmf2pZKiIuSscJMZfVypjJrViK3XCiubmT8jdTn3lS7qoYwGg+Iu7rtjMmL3zFaxuia0YKX6GVTGtilhcMYf+8V2HEvTZfzUlA0sQK68Pck4lS6DLhCdS1/sqjMrQ+z4IwVIZ9Kh4nY86ASCf6pifN6ttU3zHhFCMmib0JcRXMlJAfdhqeW7Tm2shdDN1ZDXjaBac553VAmevnEVC81xUXsybYlaYEPuYdL87h8IW4UrC0AmhM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/malc0de.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
