env:
  global:
    - secure: qC+YYFulm6aBBmxEvhPFItokkNEWzaEBOxPD+8g6tqiIsBOhCl/Y9KHJuEnNwAnSC1wqlPmgnm1rJgtBr9PfnrDzEwmSUEcYRBeZ4Oi6oTW6OEiCer/xCrvld/k+Vu8rnLxVbO8IpvyIC0/lu8CAYOTJESleZE5w/4IgR+DVGf7zumk/6dXFTgZ5RZB98ialpYpYFcY5oYj3+oV+T5Q4yL6ooebRC1O3KhoBxe8flAQAx7UsvZ2KhmCc2TX9Gq2/vrGSGDNhfxK3srqaBheoHyagDGp2HOk0wRpxih8RYOXLpQmE3jaUD+nR7xoLEpgvkciKC1d06tePwOnoz1KZWmyYFm0oG7djEY+NXGlzIVTc/VU35AdynlOOFwV7sB1qJw1kaSi/O2b5vE/ElBawiRmB/ezh3VVP6zFor+V++PoXdwa10Yhp72MZnP5cTT10qqB7k1hxjqO+sp+O1v8mBV3ps/0gsHqVWFE3sdlqhtoWiCZ/W9OVoNIWGzNvGCC3G/OUJ3habYa+tXkhosWJ8W3mWPmEPw2z05EWqvuQ26XqlHOj+SfjSEHpL6aASz7yFtElXCHXENG2JKTodDyUpS22uwQgXHwyAPoK6YlT9rT+lEEEK/r7OS6oGL/YZE17R+TQdtM4PIfxwXtwtvOGpVhKU4VQtmTl8Oi2ds39+7Y=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/malc0de.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
